version: '2'

services:
    web:
        container_name: web
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - angular_app:/www:ro
        networks:
            - appnet
    angular-builder:
        container_name: angular-builder
        build:
            context: ./code-web/
            args:
                - http_proxy=http://pac.tsl.telus.com:8080
                - https_proxy=http://pac.tsl.telus.com:8080
                - NG_ENV=development
        volumes:
            - angular_app:/src/dist
    node:
        container_name: node
        build:
            context: ./code-api/
            args:
                - http_proxy=http://pac.tsl.telus.com:8080
                - https_proxy=http://pac.tsl.telus.com:8080
        networks:
            - appnet
        depends_on:
          - db
    db:
        container_name: db
        image: mongo:latest
        restart: always
        volumes:
          - mongo_data:/data/db
        networks:
          - appnet
networks:
  appnet:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  angular_app:
    driver: local
